version: '3.8'

services:
  adr-workbench:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./plugins:/app/plugins
      - ./docs:/app/docs
      - adr-data:/app/data
    environment:
      - DEBUG=true
      - DATABASE_URL=sqlite+aiosqlite:///./data/adr_workbench.db
    restart: unless-stopped

volumes:
  adr-data:
